name: Build & Test

on: [push, pull_request]
  
jobs:
  build:

    runs-on: windows-latest
  
    defaults:
      run:
        working-directory: .
    
    outputs:
      semver: ${{ steps.gitversion.outputs.semver }}
      semver2: ${{ steps.gitver.outputs.semver2 }}
      LicenseClearingTool: ${{ steps.packageBuildResults.outputs.LicenseClearingTool }}
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
   
   
    - name: Store SemVer
      if: ${{ false }}  # disable for now
      #id: gitversion
      run: |
          Write-Host "::set-output name=semver::$($env:GitVersion_SemVer)"
          
    - name: Determine Version
      #if: ${{ false }}  # disable for now
      uses: gittools/actions/gitversion/execute@v0.9.7
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: TRUE

    - name: get SemVer 
      #if: ${{ false }}  # disable for now
      #id: gitversion
      run: |
        echo "SemVer: $($env:GitVersion_SemVer)" 
        Write-Host "::set-output name=semver::$($env:GitVersion_SemVer)"
        Write-Host $semver
        $fileName = "dummy-$($env:GitVersion_SemVer)"
        Write-Host "Filename: '$fileName'"
        
    - name: Gitversion   
      #if: ${{ false }}  # disable for now
      id: gitver      
      run: |
        dotnet tool install --global GitVersion.Tool --version 5.3.6
        dotnet gitversion /output buildserver /nofetch
        dotnet gitversion /output file /outputfile version.json
        
        Write-Host "::set-output name=semver2::$($env:GitVersion_SemVer)"
        Write-Host $semver2
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: TRUE
        
    - name: Store SemVer
      if: ${{ false }}  # disable for now
      run: |
          Write-Host "::set-output name=semver::$($env:GitVersion_SemVer)"
          Write-Host $semver
          $fileName = "dummy-$($env:GitVersion_SemVer)"
          Write-Host "Filename: '$fileName'"
          
    - name: Restore Packages
      run: dotnet restore src\LicenseClearingTool.sln 
    
    - name: Build
      run: msbuild -m -t:Rebuild -p:Configuration=Release -bl:continous-clearing.binlog -noconlog src\LicenseClearingTool.sln
  
