name: Build & Test

on: [push, pull_request]
  
jobs:
  build:

    runs-on: self-hosted
  
    defaults:
      run:
        working-directory: ./src
    
    outputs:
      semver: ${{ steps.gitversion.outputs.semver }}
      LicenseClearingTool: ${{ steps.packageBuildResults.outputs.LicenseClearingTool }}
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
    
     
    - name: Determine Version
      #if: ${{ false }}  # disable for now
      uses: gittools/actions/gitversion/execute@v0.9.7
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: TRUE

    - name: Display SemVer      
      run: |
        echo "SemVer: $($env:GitVersion_SemVer)" 
     
    - name: Gitversion    
      id: gitversion
      run: |
        dotnet tool install --global GitVersion.Tool --version 5.3.6
        dotnet gitversion /output buildserver /nofetch
        dotnet gitversion /output file /outputfile version.json
        
        Write-Host "::set-output name=semver2::$($env:GitVersion_SemVer)"
        Write-Host "$semver2"
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: TRUE
        
    - name: Store SemVer
      run: |
          Write-Host "::set-output name=semver::$($env:GitVersion_SemVer)"
          Write-Host "$semver"
     
  
