name: Publish Pacakges

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  publish:
    runs-on: self-hosted
    
    steps:
      - name: Download NuGet Packages from Release
        run: |
            Write-Host "GITHUB_REF: '$($env:GITHUB_REF)'"
            $prefix = "refs/tags/"
            $name = $($env:GITHUB_REF).Substring($prefix.Length)
            Write-Host "name: '$name'"
            gh release download $name --repo siemens/continuous-clearing --pattern '*.nupkg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish to NuGet.org
        run: |
          dotnet nuget push "*.nupkg" --api-key $env:PAT_GITHUB --source "https://nuget.pkg.github.com/siemens/index.json" --clobber
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
